export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_FULL_PRODUCTS_LIST = 'GET_FULL_PRODUCTS_LIST';
export const GET_PRODUCT_DATA = 'GET_PRODUCT_DATA';
export const SEND_ORDER = 'SEND_ORDER';
export const GET_ORDER = 'GET_ORDER';
