export const START_FETCH = 'START_FETCH';
export const END_FETCH = 'END_FETCH'; 
export const SAVE_SEARCH_PRODUCTS = 'SAVE_SEARCH_PRODUCTS';
export const CLEAR_SEARCH_PRODUCTS = 'CLEAR_SEARCH_PRODUCTS';
